Additional_wallpapers/Squam_Lake-bw.jpg		usr/local/share/backgrounds/MX15/wallpaper
Additional_wallpapers/Squam_Lake-Dark.jpg	usr/local/share/backgrounds/MX15/wallpaper
Live_bootloader/back640.jpg			usr/local/share/backgrounds/MX15/syslinux
Live_bootloader/back800.jpg			usr/local/share/backgrounds/MX15/syslinux
Live_bootloader/back1024.jpg			usr/local/share/backgrounds/MX15/syslinux
Live_bootloader/README				usr/local/share/backgrounds/MX15/syslinux
